import {
  AirVent,
  FlameKindling,
  Flower,
  ShowerHead,
  Snowflake,
  Tv,
  Vault,
  View,
  WashingMachine,
  WifiIcon,
  Refrigerator,
  SquareParking,
  Coffee,
  Bath,
  LampDesk,
  ShipWheel,
  Phone,
  Shirt,
  Sofa,
  ChefHat,
  Microwave,
  CookingPot,
  CirclePower,
} from 'lucide-react';

const amenities = [
  { id: 'wifi', text: 'Wifi', icon: WifiIcon },
  { id: 'tv', text: 'TV', icon: Tv },
  { id: 'fireplace', text: 'Fireplace', icon: FlameKindling },
  { id: 'spa_wellness', text: 'Spa & Wellness', icon: Flower },
  { id: 'air-conditioning', text: 'Air Conditioning', icon: AirVent },
  { id: 'minibar', text: 'Minibar', icon: Snowflake },
  { id: 'balcony', text: 'Balcony' },
  { id: 'shower', text: 'Shower', icon: ShowerHead },
  { id: 'bathtub', text: 'Bathtub', icon: Bath },
  { id: 'washing-machine', text: 'Washing Machine', icon: WashingMachine },
  { id: 'hairdryer', text: 'Hairdryer' },
  { id: 'desk', text: 'Desk', icon: LampDesk },
  { id: 'safe', text: 'Safe', icon: Vault },
  { id: 'sea-view', text: 'Sea View', icon: ShipWheel },
  { id: 'great-view', text: 'Great View', icon: View },
  { id: 'telephone', text: 'Telephone', icon: Phone },
  { id: 'closet', text: 'Closet', icon: Shirt },
  { id: 'iron', text: 'Iron' },
  { id: 'sofa', text: 'Sofa', icon: Sofa },
  { id: 'kitchen', text: 'Kitchen', icon: CookingPot },
  { id: 'microwave', text: 'Microwave', icon: Microwave },
  { id: 'refrigerator', text: 'Refrigerator', icon: Refrigerator },
  { id: 'parking', text: 'Parking', icon: SquareParking },
  { id: 'oven', text: 'Oven', icon: ChefHat },
  { id: 'stovetop', text: 'Stovetop', icon: CirclePower },
  { id: 'coffee-machine', text: 'Coffee Machine', icon: Coffee },
];

export default amenities;
